name: esp32
on: [push, pull_request]
jobs:
  build:
    name: Test compile examples for esp32
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Approximate
      uses: actions/checkout@v2
      with:
        repository: davidchatting/Approximate
        ref: master
        path: CustomListLib

    - name: Checkout SevSeg
      uses: actions/checkout@v2
      with:
        repository: DeanIsMe/SevSeg
        ref: master
        path: CustomListLib

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@master
      with:
        arduino-board-fqbn: esp32:esp32:esp32
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        extra-arduino-cli-args: "--warnings default"
